---
title: "16S bootcamp data treatment"
author: "Martin Andersen"
date: "25 sep 2017"
output: html_document
---
# Libraries
```{r}
library(ggplot2)
library(dplyr)
library(reshape2)
```



# Load fastq files

Run ID:
```{r}
runID <- "fastq_runid_a93bffab6d35662ac042b24bd7b7e5ddbf6ca700_0"
```

### Function
```{r}
process_fastq <- function(x) {
  x_s <- select(x, c(1,3,5,6))
  x_s <- x_s[seq(1, nrow(x_s), 4), ]
  barcode <- sub(".*([0-9].*?)", "", x_s$V6)
  read_time <- sub(".*T(.*?)Z", "\\1", x_s$V5)
  read_date <- sub(".*=(.*?)T.*", "\\1", x_s$V5)
  read_no <- sub(".*=", "\\1", x_s$V3)
  read_datetime <- as.POSIXct(paste(read_date, read_time), format = "%Y-%m-%d %H:%M:%S")
  read_id <- x_s[,1]
  x_d <- tibble(barcode, read_id, read_no, read_datetime)
  colnames(x_d) <- c("barcode", "read_ID", "read_no", "read_datetime")
  return(x_d)
}
```

### Barcode 1
```{r}
bar1_s <- read.delim(paste0("16S/pass/barcode01/", runID, ".fastq"), header = FALSE, sep = "") %>%
  process_fastq()

```

### Barcode 2
```{r}
bar2_s <- read.delim(paste0("16S/pass/barcode02/", runID,".fastq"), header = FALSE, sep = "") %>%
  process_fastq()
```

### Barcode 3
```{r}
bar3_s <- read.delim(paste0("16S/pass/barcode03/", runID, ".fastq"), header = FALSE, sep = "") %>%
  process_fastq()
```

### Barcode 4
```{r}
bar4_s <- read.delim(paste0("16S/pass/barcode04/", runID, ".fastq"), header = FALSE, sep = "") %>%
  process_fastq()
```

### Combined
```{r}
data <- rbind(bar1_s, bar2_s, bar3_s, bar4_s)
```

# Plots
## Number of reads
```{r}

```

